In [1]:
import numpy as np

#### Vectors and Matrix

In [2]:
#create a 2x2 array

a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a.shape

(2, 2)

In [5]:
a.dtype

dtype('int32')

In [6]:
a.shape

(2, 2)

In [7]:
#dimension

a.ndim # row and columns are considered. 

2

In [8]:
type(a)     #nd = n dimensions

numpy.ndarray

In [9]:
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
b = np.ones((3,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
c = np.full((3,5),5)
c

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### Numpy array with random values

In [12]:
a = np.random.random((3,5))
a

array([[0.20093557, 0.07904388, 0.76217085, 0.17406725, 0.99427901],
       [0.22800285, 0.20754973, 0.57872352, 0.06189897, 0.97746341],
       [0.65362124, 0.61854587, 0.70741356, 0.77097644, 0.97800401]])

In [13]:
b = np.random.randint(0,50,(3,5))
b

array([[ 1,  9,  1, 46, 11],
       [29, 24, 32, 32, 49],
       [49, 33, 26,  8, 35]])

### Numpy array with particular range

In [14]:
a = np.arange(0,50,10)
a

array([ 0, 10, 20, 30, 40])

### linspace

In [15]:
b = np.linspace(0,30,10)
b

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

### Operators in Numpy array

In [16]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [17]:
a+1

array([[2, 3],
       [4, 5]])

In [18]:
a-2

array([[-1,  0],
       [ 1,  2]])

In [19]:
a*5

array([[ 5, 10],
       [15, 20]])

In [20]:
a/1

array([[1., 2.],
       [3., 4.]])

In [21]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [22]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [23]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [24]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [25]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [26]:
#exponential
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
np.sum(a)

10

In [29]:
np.min(a)

1

In [30]:
np.max(a)

4

In [31]:
#col

np.min(a,axis = 0)

array([1, 2])

In [32]:
np.max(a,axis = 0)

array([3, 4])

In [33]:
#row

np.min(a,axis = 1)

array([1, 3])

In [34]:
np.max(a,axis = 1)

array([2, 4])

In [35]:
a = np.array([[4,3],[9,1]])

In [36]:
np.sort(a)

array([[3, 4],
       [1, 9]])

In [37]:
np.sort(a,axis = 0)

array([[4, 1],
       [9, 3]])

### For Matrix Multiplication there are two methods.. matmul and dot.

In [38]:
a = np.array([[5,6],[4,2]])
b  = np.array([[1,3],[2,6]])

In [39]:
a

array([[5, 6],
       [4, 2]])

In [40]:
b

array([[1, 3],
       [2, 6]])

In [41]:
print(np.matmul(a,b))

[[17 51]
 [ 8 24]]


In [42]:
print(np.dot(a,b))

[[17 51]
 [ 8 24]]


In [43]:
a.T

array([[5, 4],
       [6, 2]])

In [44]:
a = np.linspace(1,20, 12)
a

array([ 1.        ,  2.72727273,  4.45454545,  6.18181818,  7.90909091,
        9.63636364, 11.36363636, 13.09090909, 14.81818182, 16.54545455,
       18.27272727, 20.        ])

In [45]:
a.shape

(12,)

In [49]:
a =a.reshape(3,4)

In [50]:
a

array([[ 1.        ,  2.72727273,  4.45454545,  6.18181818],
       [ 7.90909091,  9.63636364, 11.36363636, 13.09090909],
       [14.81818182, 16.54545455, 18.27272727, 20.        ]])

In [51]:
a.shape

(3, 4)

### Vstack and Hstack

In [56]:
b = np.random.randint(1,10,(3,3))
b

array([[5, 3, 1],
       [2, 6, 4],
       [4, 2, 5]])

In [57]:
b = b.reshape(1,-1)
b

array([[5, 3, 1, 2, 6, 4, 4, 2, 5]])

In [59]:
b = b.reshape(-1,1)
b

array([[5],
       [3],
       [1],
       [2],
       [6],
       [4],
       [4],
       [2],
       [5]])

In [60]:
a = np.zeros((5,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [61]:
a = a.flatten()
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Slicing

In [62]:
a = np.random.randint(1,10,(3,3))
a

array([[3, 7, 5],
       [3, 7, 2],
       [3, 2, 5]])

In [63]:
a[1:2,1:]

array([[7, 2]])

In [65]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a[1:2,1:]

array([[5, 6]])

In [104]:
a[0:1,0]

array([1])

In [72]:
a[:1,2:]

array([[3]])

In [108]:
a[2:,0]

array([7])

In [109]:
a[2:,2]

array([9])

In [90]:
a[:1,1]

array([2])

In [95]:
a[1:2,0]

array([4])

In [99]:
a[1:2,2]

array([6])

In [78]:
a[2:,1]

array([8])

In [101]:
a[1:2,1]

array([5])

In [83]:
a[0:1]

array([[1, 2, 3]])

In [82]:
a[2:]

array([[7, 8, 9]])