In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
col_1 = np.array([10,20,30,40,50,60,70,80,90])
col_2 = np.array([15,25,35,45,55,65,75,85,95])

In [3]:
out = []
for i in range(len(col_1)):
    out.append(col_1[i]+col_2[i])
out_col = np.array(out)

In [4]:
out_col = np.array([col_1[i]+col_2[i] for i in range(len(col_1))])

In [5]:
out_col

array([ 25,  45,  65,  85, 105, 125, 145, 165, 185])

In [8]:
#converting ek ek column mei
col_1 = col_1.reshape(len(col_1),1)
col_2 = col_2.reshape(len(col_2),1)
out_col = out_col.reshape(len(out_col),1)

In [9]:
data = np.hstack((col_1,col_2,out_col))

In [10]:
data

array([[ 10,  15,  25],
       [ 20,  25,  45],
       [ 30,  35,  65],
       [ 40,  45,  85],
       [ 50,  55, 105],
       [ 60,  65, 125],
       [ 70,  75, 145],
       [ 80,  85, 165],
       [ 90,  95, 185]])

In [17]:
# coverting into features and target data
def feature_transform(n_steps, data):
    x = []
    y = []
    for i in range(n_steps,len(data)+1):
        x.append(data[i-n_steps:i,:-1]) #last value chodh k sahbhi values lene hai 
        y.append(data[i-1,-1])
    return np.array(x), np.array(y)

In [18]:
n_steps = 3
x,y = feature_transform(n_steps,data)

In [20]:
x

array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[20, 25],
        [30, 35],
        [40, 45]],

       [[30, 35],
        [40, 45],
        [50, 55]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[50, 55],
        [60, 65],
        [70, 75]],

       [[60, 65],
        [70, 75],
        [80, 85]],

       [[70, 75],
        [80, 85],
        [90, 95]]])

In [21]:
y

array([ 65,  85, 105, 125, 145, 165, 185])

In [22]:
from keras.layers import LSTM, Dense
from keras.models import Sequential

In [23]:
x.shape

(7, 3, 2)

In [25]:
model = Sequential()
model.add(LSTM(50, activation = "relu", input_shape = (n_steps,x.shape[2])))
model.add(Dense(1))
model.compile(optimizer = "adam",loss = "mean_squared_error")

In [26]:
#training
history = model.fit(x,y,epochs = 100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 18241.2676
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 17681.8730
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 17157.1465
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 16674.2129
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 16224.1357
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 15789.3701
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 15349.1396
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 14883.2705
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 14377.8594
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 13841.1348
Epoch 11/100
1/1 [==============================] - 0s 8ms/step - loss: 13306.4844
Epoch 12/100
1/1 [==============================] - 0s 5ms/step - loss: 12799.1084
Epoch 13/100
1

In [28]:
#testing
xtest = np.array([[80,85],[90,95],[100,105]])
xtest.shape

(3, 2)

In [30]:
xtest = xtest.reshape(1,n_steps,2)
xtest.shape

(1, 3, 2)

In [32]:
ypred = model.predict(xtest)
ypred

array([[208.30563]], dtype=float32)