### SVD (Singular Value Decomposition)

***Matrix Decomposition Method.****

Suppose we have a matrix of 2x2 [(d1,d2),(d3,d4)] ->  we going to get decomposed/subsequent matrix. 

```We'll get U, V, S```

SVD -> returns 3 matrixes:
- ***U:*** Eigen Vector
- ***Sigma:*** diagonal matrix of singular values (root of the eigen values)
- ***V:*** Eigen Vector

- Normally used in Image Compression.

##### Mathematical Representation / Steps:
SVD Formula:

data (which is a matrix of any dimension) = USV^T
***A = USV^T***

##### Calculating U:
U = A x $A^T$ (T is the transpose)

##### Calculating V:
V = $A^T$ x A 

##### Calculating S:
S = $\sqrt \lambda$ (Lamda is Eigen Values)

##### Eg:
Let's say A is a matrix of m rows and n columns:

$A_{mxn}$ = $U_{mxm}$ * $S_{mxn}$ * $V^T$$_{nxn}$

### SVD for Dimension Reduction

A = U x Sigma x $V^T$

T = U x Sigma

***T = data x ($V^T$ x T)***

This transforms the data in lower dimensions. 

In [1]:
import numpy as np

In [2]:
A = np.array([[-1,2,0],[2,0,1],[0,-2,1]])
A

array([[-1,  2,  0],
       [ 2,  0,  1],
       [ 0, -2,  1]])

### Calculate U, S and VT

In [3]:
from numpy.linalg import svd

U,S,VT = svd(A)

In [4]:
U

array([[-0.67028426, -0.14157742,  0.72847433],
       [ 0.39926415, -0.89625169,  0.19318659],
       [ 0.62554549,  0.42034361,  0.65727018]])

In [5]:
S #sigma not in diagonal form

array([3.15029268, 2.05306258, 0.92767992])

In [6]:
VT

array([[ 0.46624638, -0.8226726 ,  0.32530617],
       [-0.80412841, -0.54739786, -0.23180398],
       [-0.36877068,  0.15351016,  0.91675668]])

In [7]:
sigma = np.zeros(A.shape)
sigma

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# now put the value of S diagonally. For that we'll have to slice it.

sigma[:A.shape[0],:A.shape[0]] = np.diag (S)

In [9]:
sigma

array([[3.15029268, 0.        , 0.        ],
       [0.        , 2.05306258, 0.        ],
       [0.        , 0.        , 0.92767992]])

In [10]:
T = U.dot(sigma)

In [11]:
T

array([[-2.11159159, -0.2906673 ,  0.67579101],
       [ 1.25779892, -1.8400608 ,  0.17921532],
       [ 1.97065138,  0.86299174,  0.60973635]])

In [12]:
T = A.dot(VT.T)

In [13]:
# data After Transformation

T

array([[-2.11159159, -0.2906673 ,  0.67579101],
       [ 1.25779892, -1.8400608 ,  0.17921532],
       [ 1.97065138,  0.86299174,  0.60973635]])

### SVD using Scikit-Learn

### Truncated SVD

In [14]:
from sklearn.decomposition import TruncatedSVD

In [15]:
svd = TruncatedSVD()
svd.fit(A)
T = svd.transform(A)
T

array([[ 2.11159159,  0.2906673 ],
       [-1.25779892,  1.8400608 ],
       [-1.97065138, -0.86299174]])

In [16]:
svd.singular_values_

array([3.15029268, 2.05306258])

### Randomized SVD

In [17]:
from sklearn.utils.extmath import randomized_svd

In [18]:
U, S, VT =  randomized_svd(A, n_components = 2)

In [19]:
U

array([[ 0.67028426,  0.14157742],
       [-0.39926415,  0.89625169],
       [-0.62554549, -0.42034361]])

In [20]:
np.diag(S)

array([[3.15029268, 0.        ],
       [0.        , 2.05306258]])

In [21]:
VT

array([[-0.46624638,  0.8226726 , -0.32530617],
       [ 0.80412841,  0.54739786,  0.23180398]])