In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Ad_purchace.csv")

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
data["Gender"] = data["Gender"].map({"Male":0,"Female":1})

In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0

In [7]:
x = data.drop(columns = ["User ID","Purchased"])
y = data["Purchased"]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size = 0.2)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
model = KNeighborsClassifier(n_neighbors = 5)

In [12]:
model.fit(xtrain,ytrain)

KNeighborsClassifier()

In [13]:
ypred = model.predict(xtest)
ypred

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
acc = accuracy_score(ytest,ypred)

In [15]:
acc

0.8375

In [16]:
cm = confusion_matrix(ytest,ypred)
cm

array([[50,  5],
       [ 8, 17]], dtype=int64)

In [17]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.86      0.91      0.88        55
           1       0.77      0.68      0.72        25

    accuracy                           0.84        80
   macro avg       0.82      0.79      0.80        80
weighted avg       0.83      0.84      0.83        80



In [18]:
from sklearn.preprocessing import StandardScaler
sc =  StandardScaler()
scale_x = sc.fit_transform(x)

In [19]:
model_sc = KNeighborsClassifier(n_neighbors = 5)
model_sc.fit(xtrain,ytrain)
ypred = model_sc.predict(xtest)
ypred

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [20]:
acc = accuracy_score(ytest,ypred)
acc

0.8375

In [21]:
cm = confusion_matrix(ytest,ypred)
cm

array([[50,  5],
       [ 8, 17]], dtype=int64)

In [22]:
#estimator
model = KNeighborsClassifier()

In [23]:
#parameter
n_neighbors = range(1,10)
metric = ['euclidean',"manhattan","minkowski"]
weights = ["uniform","distance"]

In [24]:
#parameter grid
grid={"n_neighbors":n_neighbors,"metric":metric,"weights":weights}

In [25]:
from sklearn.model_selection import RepeatedStratifiedKFold

In [26]:
kfold_cv = RepeatedStratifiedKFold (n_splits = 5, n_repeats = 3, random_state = 0)

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
grid_cv = GridSearchCV(estimator = model, param_grid = grid, cv = kfold_cv, scoring = "accuracy",n_jobs = 1)

In [29]:
res = grid_cv.fit(xtrain,ytrain)

In [30]:
res.best_params_

{'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'}

In [31]:
res.best_score_

0.8166666666666667